-- 创建外部用户数据关联表，关联到 wx_users 表
CREATE TABLE IF NOT EXISTS `external_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '外部用户数据ID',
  `wx_user_id` INT(11) NOT NULL COMMENT '关联的wx_users表用户ID',
  `usn` VARCHAR(64) NOT NULL COMMENT '外部系统用户唯一标识',
  `external_user_id` VARCHAR(50) DEFAULT NULL COMMENT '外部系统用户ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `truename` VARCHAR(100) DEFAULT NULL COMMENT '真实姓名',
  `nickname` VARCHAR(100) DEFAULT NULL COMMENT '昵称',
  `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `avatar` TEXT DEFAULT NULL COMMENT '头像URL',
  `access_token` TEXT DEFAULT NULL COMMENT '访问令牌',
  `refresh_token` TEXT DEFAULT NULL COMMENT '刷新令牌',
  `ws_token` VARCHAR(255) DEFAULT NULL COMMENT 'WebSocket令牌',
  `node_org` VARCHAR(64) DEFAULT NULL COMMENT '节点组织',
  `im_token` VARCHAR(255) DEFAULT NULL COMMENT 'IM令牌',
  `identity_authentication` VARCHAR(10) DEFAULT NULL COMMENT '身份认证状态',
  `postcode` VARCHAR(20) DEFAULT NULL COMMENT '邮编',
  `nation` VARCHAR(50) DEFAULT NULL COMMENT '国家/地区',
  `invite_code` VARCHAR(20) DEFAULT NULL COMMENT '邀请码',
  `channel` VARCHAR(50) DEFAULT NULL COMMENT '渠道',
  `chain_status` VARCHAR(10) DEFAULT NULL COMMENT '链状态',
  `status` INT(11) DEFAULT 0 COMMENT '用户状态',
  `id_card_no` VARCHAR(50) DEFAULT NULL COMMENT '身份证号',
  `created_at` DATETIME DEFAULT NULL COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_usn` (`usn`),
  UNIQUE KEY `uk_wx_user_id` (`wx_user_id`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_external_user_id` (`external_user_id`),
  CONSTRAINT `fk_external_users_wx_user` FOREIGN KEY (`wx_user_id`) REFERENCES `wx_users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外部用户数据表，关联wx_users';

