-- 创建商家表
CREATE TABLE IF NOT EXISTS merchants (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL COMMENT '商家名称',
  logo VARCHAR(255) COMMENT '商家logo',
  description TEXT COMMENT '商家描述',
  address VARCHAR(255) COMMENT '商家地址',
  phone VARCHAR(20) COMMENT '商家电话',
  status ENUM('active', 'inactive') DEFAULT 'active' COMMENT '商家状态',
  sort_order INT DEFAULT 0 COMMENT '排序',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家表';

-- 创建商家图片表
CREATE TABLE IF NOT EXISTS merchant_images (
  id INT PRIMARY KEY AUTO_INCREMENT,
  merchant_id INT NOT NULL COMMENT '商家ID',
  image_url VARCHAR(255) NOT NULL COMMENT '图片URL',
  sort_order INT DEFAULT 0 COMMENT '排序',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家图片表'; 