/** 写入 Redis 的外部用户快照（不含 token / 密钥类字段） */
function buildExternalUserRedisCachePayload({
  id,
  wx_user_id,
  usn,
  external_user_id,
  username,
  truename,
  nickname,
  mobile,
  avatar,
  expire,
  app_type,
  app_type_name,
  set_password,
  node_org,
  identity_authentication,
  postcode,
  nation,
  invite_code,
  channel,
  client_id,
  privileges,
  chain_status,
  status,
  id_card_no,
}) {
  return {
    id,
    wx_user_id,
    usn,
    external_user_id,
    username,
    truename,
    nickname,
    mobile,
    avatar,
    expire,
    app_type,
    app_type_name,
    set_password,
    node_org,
    identity_authentication,
    postcode,
    nation,
    invite_code,
    channel,
    client_id,
    privileges,
    chain_status,
    status,
    id_card_no,
  }
}

module.exports = {
  buildExternalUserRedisCachePayload,
}
